### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by improve100** [gaunthan/leanote2md#2]
Python 3.5.2
xx@xxx-PC:~/leanote2md$ ./exporter.py config.py
Login success, welcome admin (admin@leanote.com).
Traceback (most recent call last):
  File "./exporter.py", line 208, in <module>
    localize_image=True, forced_save=False, only_blog=only_blog)
  File "./exporter.py", line 143, in save_note_as_md
    mkdir_p(final_path)
  File "/home/xxx/leanote2md/utils.py", line 11, in mkdir_p
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 226, in makedirs
    head, tail = path.split(name)
  File "/usr/lib/python3.5/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
AttributeError: 'PosixPath' object has no attribute 'rfind'

**Comment by gaunthan** [comment]
Support for Path objects in the os module was added in Python 3.6. Please use Python 3.6.
