### ISSUE TITLE
无法正常使用，请求帮助

### ISSUE THREAD

**Issue by MutingLeng** [gaunthan/leanote2md#4]
运行环境： Debian 9，python --version 3.5.1，pip3 --version pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)

leanote自建，已修改```lea.py```的```LEANOTE_API_BASE```。用户名、密码、导出目录均已输入，但运行后报错如下，能看得出来已经登录成功。我并不是软件开发人员，请见谅。

```bash
Login success, welcome XXX (XXX@XXX).
Traceback (most recent call last):
  File "./exporter.py", line 208, in <module>
    localize_image=True, forced_save=False, only_blog=only_blog)
  File "./exporter.py", line 143, in save_note_as_md
    mkdir_p(final_path)
  File "/root/leanote2md/utils.py", line 11, in mkdir_p
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 226, in makedirs
    head, tail = path.split(name)
  File "/usr/lib/python3.5/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
AttributeError: 'PosixPath' object has no attribute 'rfind'

```

**Comment by gaunthan** [comment]
请使用Python 3.6
